apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
  namespace: mlflow
type: Opaque
stringData:
  MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow_password@mlflow-db-shrinidhi.c722o6ki0gwv.ap-northeast-3.rds.amazonaws.com:5432/mlflow?sslmode=require