apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
  namespace: mlflow
type: Opaque
stringData:
  MLFLOW_BACKEND_STORE_URI: postgresql://<username>:<password>@<database-endpoint>:<port>/<database-name>?sslmode=require